train_data_path: '../data/train_center'
valid_data_path: '../data/Valid'
net_save_path: './net_param/Conv3DV7_9_first_super/3DynRec_net_Conv3D'
var_save_path: './Vardata/Conv3DV7/Conv3DV7_9_first_super.pckl'
net_load_path: './net_param/Conv3DV7_9_first_super/3DynRec_net_Conv3D_epch499.pth'
# './net_param/saved_net/V7_9/first_super/3DynRec_net_Conv3D_epch499.pth'
# './net_param/Conv3DV7_9_first_super/3DynRec_net_Conv3D_epch75.pth'

SpDim: 93
HidDim: [48, 24, 12, 12]
KnnC: 20
Knn: 10
lr: 0.001
param: [0.1, 0.05]
NumEpoch: 500

Aff: 'Euc'
Train_Ver: 'super'

Semantic: True
net_load: True
Cadd: False

