train_data_path: '../data/train_center_PN'
valid_data_path: '../data/Valid'
net_save_path: './net_param/Conv3DV7_9_first_super_PN_Cadd/3DynRec_net_Conv3D'
var_save_path: './Vardata/Conv3DV7/Conv3DV7_9_first_super.pckl'
net_load_path: './net_param/Conv3DV7_9_super_first_PN_Cadd/3DynRec_net_Conv3D_epch35.pth'

SpDim: 30
HidDim: [30, 24, 12, 12]
DimP: [30, 120, 48]
KnnC: 20
Knn: 10
lr: 0.001
param: [0.1, 0.02]
NumEpoch: 500

Aff: 'Euc'
Train_Ver: 'super'

Semantic: True
net_load: True
Cadd: True

