train_data_path: '../data/train_center_PN'
valid_data_path: '../data/Valid'
net_save_path: './net_param/Conv3DV7_9_super_first_PN/3DynRec_net_Conv3D'
var_save_path: './Vardata/Conv3DV7/Conv3DV7_9_super_first_PN.pckl'
net_load_path: ''

SpDim: 30
HidDim: [30, 24, 12, 12]
KnnC: 20
Knn: 10
lr: 0.001
param: [1.0, 0.5]
NumEpoch: 500

Aff: 'Euc'
Train_Ver: 'super_first'

Semantic: True
net_load: False
Cadd: False

