train_data_path: '../data/train_center'
valid_data_path: '../data/Valid'
net_save_path: './net_param/Conv3DV7_9_super_full/3DynRec_net_Conv3D'
var_save_path: './Vardata/Conv3DV7/Conv3DV7_9_super.pckl'
net_load_path: ''

SpDim: 93
HidDim: [48, 24, 12, 12]
KnnC: 10
Knn: 10
lr: 0.01
param: [1.0, 1.0, 1.0]
NumEpoch: 500

Aff: 'Euc'
Train_Ver: 'super'

Semantic: True
net_load: False
Cadd: False
