train_data_path: '../data/train_center_full'
valid_data_path: '../data/Valid'
net_save_path: './net_param/Conv3DV7_9_unsuper_full/3DynRec_net_Conv3D'
var_save_path: './Vardata/Conv3DV7/Conv3DV7_9_unsuper.pckl'
net_load_path: ''

SpDim: 93
HidDim: [48, 24, 12, 12]
KnnC: 20
Knn: 10
lr: 0.01
param: [0.1, 0.1]
NumEpoch: 500

Aff: 'Euc'
Train_Ver: 'unsuper'

Semantic: True
net_load: False
Cadd: False
